language: elixir
services:
  - docker
env:
  matrix:
    DB=mysql:5.7
matrix:
  include:
    - elixir: 1.4.3
      otp_release: 20.3
    - elixir: 1.7.3
      otp_release: 21.1
before_install:
  - sudo service mysql stop
  - docker pull $DB || true
  - docker run --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -d $DB
