language: elixir
services:
  - docker
elixir: 1.7
otp_release: 21.1
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-client
env:
  matrix:
    - DB=mysql:5.7
    - DB=mysql:8.0
matrix:
  include:
    - elixir: 1.4
      otp_release: 18.3
before_install:
  - docker pull $DB || true
  - sudo chmod 777 -R /var/run/mysqld
  - docker run --name mysql -p 3306:3306 --volume /var/run/mysqld:/var/run/mysqld -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -d $DB
  - mysql --version
  - until mysql -u root -e "SELECT @@version;"; do sleep 1; done
